### ISSUE TITLE
projections handling users adding food points

### ISSUE THREAD

**Issue by howardc93** [howardc93/foodpoints#19]
Currently the projection just takes the first and last balance of the user within the current semester and projects using this.

However if the user adds food points, these projections are too low.  We could calculate the projections by summing only negative transactions between the first/last range.

**Comment by viddamao** [comment]
Will it work if we get the positive transactions and make multiple projections split based on the date that user adds foodpoints?

**Comment by howardc93** [comment]
maybe.  But that complicates how projections work a lot.  If you want to try to implement feel free to go ahead

**Comment by viddamao** [comment]
sorry...pushed to wrong branch...my bad...

**Comment by howardc93** [comment]
Yeah, production is broken (a bit).  I've rolled it back, and disabled
automatic deploy

**Comment by viddamao** [comment]
yep, just a minor prob on the total calculation, gotta fix it and pull request later

**Comment by howardc93** [comment]
Okay, do it in a new branch, PR it, and I'll manually re-deploy to
production.

**Comment by howardc93** [comment]
Does #20 fix this issue?

**Comment by viddamao** [comment]
Yep, #20 makes the projection more accurate.
and btw, I tried to make multiple line segments on the chart but turns out to be unobvious when compared to original projection line, so I guess current graph works better.
